spring:
  application:
    name: java-notes-api
  security:
    user:
      name: admin
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/secure_notes
    hikari:
      username: postgres
      password: 332003
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql
server:
  port: 4242

logging:
  level:
    org.springframework.security: DEBUG
